import os
import pandas as pd, numpy as np

PAGE_SIZE = 10
ID_HEADER = 'id'

WELL_NAME_HEADER = "Well Name"
WELL_TYPE_HEADER = "Well Type"
WELL_CONTROL_HEADER = "Well Control"
LOWER_BOUND_HEADER = "Lower Bound"
UPPER_BOUND_HEADER = "Upper Bound"
TIME_HEADER = "Time"
INIT_VALUE_HEADER = "Initial Value"
VARIABLE_NAME_ORIGINAL = "Variable Name - Original"
VARIABLE_NAME_HEADER = "Variable Name"
STANDARD_DEV = "Standard Deviation"
CORR_LENGTH = "Correlation Length"

FIXED_HEADERS = [ID_HEADER, WELL_NAME_HEADER, WELL_TYPE_HEADER,
                 WELL_CONTROL_HEADER, TIME_HEADER]

SUBSET_COLS = [ID_HEADER, VARIABLE_NAME_HEADER, TIME_HEADER, WELL_CONTROL_HEADER,
               LOWER_BOUND_HEADER, UPPER_BOUND_HEADER, INIT_VALUE_HEADER,
               STANDARD_DEV, CORR_LENGTH]

EDITABLE_COLS = [VARIABLE_NAME_HEADER, LOWER_BOUND_HEADER, UPPER_BOUND_HEADER,
                 INIT_VALUE_HEADER, STANDARD_DEV, CORR_LENGTH]